nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/':
        #knet heke el oringin http://localhost:4200
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['GET', 'POST', 'OPTIONS', 'PUT', 'DELETE']
            max_age: 3600